version: 2.1

# https://circleci.com/docs/using-matrix-jobs/#use-matrix-jobs-to-run-multiple-os-tests

orbs:
  node: circleci/node@7.1

executors:
  docker:
    docker:
      - image: cimg/base:stable
    resource_class: medium
  linux:
    machine:
      image: ubuntu-2204:2024.11.1
    resource_class: arm.medium
  macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
  # There appear to be a bug in vitest preventing test from running on windows
  # windows:
  #   machine:
  #     image: windows-server-2022-gui:current
  #   resource_class: windows.medium

jobs:
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: 22.13.1
      - run:
          name: Verify node version
          command: node -v
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Execute script
          command: npm run merge example-boards output.json

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [docker, linux, macos]
